// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'mod_nowplay.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@freezed
class NowPlayMod with _$NowPlayMod {
  const factory NowPlayMod({
    required String url,
    required String title,
    required String desc,
    required String imageUrl,
    DateTime? released,
  }) = _NowPlayMod;
}
