///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TopRateModResults {
/*
{
  "adult": false,
  "backdrop_path": "/5hNcsnMkwU2LknLoru73c76el3z.jpg",
  "genre_ids": [
    35
  ],
  "id": 19404,
  "original_language": "hi",
  "original_title": "दिलवाले दुल्हनिया ले जायेंगे",
  "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
  "popularity": 23.393,
  "poster_path": "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
  "release_date": "1995-10-20",
  "title": "Dilwale Dulhania Le Jayenge",
  "video": false,
  "vote_average": 8.7,
  "vote_count": 3418
} 
*/

  bool? adult;
  String? backdropPath;
  List<int?>? genreIds;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  TopRateModResults({
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });
  TopRateModResults.fromJson(Map<String, dynamic> json) {
    adult = json['adult'];
    backdropPath = json['backdrop_path']?.toString();
    if (json['genre_ids'] != null && (json['genre_ids'] is List)) {
      final v = json['genre_ids'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(int.parse(v.toString()));
      });
      genreIds = arr0;
    }
    id = int.tryParse(json['id']?.toString() ?? '');
    originalLanguage = json['original_language']?.toString();
    originalTitle = json['original_title']?.toString();
    overview = json['overview']?.toString();
    popularity = double.tryParse(json['popularity']?.toString() ?? '');
    posterPath = json['poster_path']?.toString();
    releaseDate = json['release_date']?.toString();
    title = json['title']?.toString();
    video = json['video'];
    voteAverage = double.tryParse(json['vote_average']?.toString() ?? '');
    voteCount = int.tryParse(json['vote_count']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['adult'] = adult;
    data['backdrop_path'] = backdropPath;
    if (genreIds != null) {
      final v = genreIds;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['genre_ids'] = arr0;
    }
    data['id'] = id;
    data['original_language'] = originalLanguage;
    data['original_title'] = originalTitle;
    data['overview'] = overview;
    data['popularity'] = popularity;
    data['poster_path'] = posterPath;
    data['release_date'] = releaseDate;
    data['title'] = title;
    data['video'] = video;
    data['vote_average'] = voteAverage;
    data['vote_count'] = voteCount;
    return data;
  }
}

class TopRateMod {
/*
{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/5hNcsnMkwU2LknLoru73c76el3z.jpg",
      "genre_ids": [
        35
      ],
      "id": 19404,
      "original_language": "hi",
      "original_title": "दिलवाले दुल्हनिया ले जायेंगे",
      "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      "popularity": 23.393,
      "poster_path": "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
      "release_date": "1995-10-20",
      "title": "Dilwale Dulhania Le Jayenge",
      "video": false,
      "vote_average": 8.7,
      "vote_count": 3418
    }
  ],
  "total_pages": 484,
  "total_results": 9663
} 
*/

  int? page;
  List<TopRateModResults?>? results;
  int? totalPages;
  int? totalResults;

  TopRateMod({
    this.page,
    this.results,
    this.totalPages,
    this.totalResults,
  });
  TopRateMod.fromJson(Map<String, dynamic> json) {
    page = int.tryParse(json['page']?.toString() ?? '');
    if (json['results'] != null && (json['results'] is List)) {
      final v = json['results'];
      final arr0 = <TopRateModResults>[];
      v.forEach((v) {
        arr0.add(TopRateModResults.fromJson(v));
      });
      results = arr0;
    }
    totalPages = int.tryParse(json['total_pages']?.toString() ?? '');
    totalResults = int.tryParse(json['total_results']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    data['total_pages'] = totalPages;
    data['total_results'] = totalResults;
    return data;
  }
}
